/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-input.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PaperInputBehavior} from './paper-input-behavior.js';

declare namespace AnypointElements {

  /**
   * `<paper-input>` single line text input styled for the Anypoint platform as a Polymer
   * powered web component
   *
   * It may include an optional error message.
   *
   * ```html
   * <paper-input required error-message="Value is required"></paper-input>
   * ```
   *
   * It may include a custom validator(s).
   *
   * ```html
   * <paper-input validator="my-validator" error-message="Value is required"></paper-input>
   * ```
   *
   * See `Anypoint.AnypointValidatableBehavior` for API and examples.
   *
   * ### Styling
   *
   * See `anypoint-text-container` for styling options.
   */
  class PaperInput extends
    Polymer.PaperInputBehavior(
    Object) {

    /**
     * Returns a reference to the focusable element. Overridden from PaperInputBehavior
     * to correctly focus the native input.
     */
    readonly _focusableElement: HTMLElement;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _onIronInputReady(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "paper-input": AnypointElements.PaperInput;
  }
}
