/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-textarea.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PaperInputBehavior} from './paper-input-behavior.js';

declare namespace AnypointElements {

  /**
   * `<paper-textarea>` is a multi line text input styled for the Anypoint platform
   * as a Polymer powered web component
   *
   * ### Example
   *
   * ```html
   * <paper-textarea></paper-textarea>
   * ```
   *
   * ### Styling
   *
   * See `anypoint-text-container` for styling options.
   */
  class PaperTextarea extends
    PaperInputBehavior(
    IronValidatableMixin(
    Object)) {
    readonly _focusableElement: any;
    value: string|null|undefined;
    _ariaDescribedBy: string|null|undefined;
    _ariaLabelledBy: string|null|undefined;
    readonly _patternRegExp: any;

    /**
     * The initial number of rows.
     */
    rows: number|null|undefined;
    _patternAlreadyChecked: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _ariaLabelledByChanged(ariaLabelledBy: any): void;
    _ariaDescribedByChanged(ariaDescribedBy: any): void;
    _onInput(): void;
    _checkPatternValidity(): any;
    _announceInvalidCharacter(message: any): void;
    _onKeypress(event: any): void;
    _isPrintable(event: any): any;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "paper-textarea": AnypointElements.PaperTextarea;
  }
}
